name: Docker Image CI

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set tag value
      id: step_one
      run: |
        echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> "$GITHUB_ENV"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: svaichu
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64, windows/amd64
        push: true
        tags: svaichu/ros2vnc:latest