name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push to DockerHub
  # You may pin to the exact commit or the version.
  # uses: MaximilianoBz/dockerhub-buildpush@372110d600041736063b948d05005b6039d8fb0c
      uses: MaximilianoBz/dockerhub-buildpush@v1.1
      env: 
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      with:
        # Docker Registry Url, eg: docker.io
        registry_url: docker.io
        # Docker Image Repository Name, eg: username/demo-app
        repository_name: svaichu/ros2vnc
        # Docker Login UserName, from: https://hub.docker.com/
        user_name: svaichu
        # Docker Login Access Token, from: https://hub.docker.com/
        password: $DOCKER_TOKEN
        # Image Build Version
        image_version: latest
        # Docker File Directory, Default Current Directory (.)
        docker_file: # optional, default is .
              
